name: connectivity_wrapper
description: A new Flutter package which provides network-aware widgets.It allows Flutter apps provide feedback on your app when it's not connected to it, or when there's no connection.
version: 1.1.0
documentation: https://github.com/ajaynonstopio/connectivity_wrapper
homepage: https://github.com/ajaynonstopio/connectivity_wrapper

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.3
  connectivity_plus: ^2.3.6  # To check connectivity for web only


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
